/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCallbackHandler: typeof import('./components/AuthCallbackHandler.vue')['default']
    GameSidebar: typeof import('./components/game/GameSidebar.vue')['default']
    LeaderboardModal: typeof import('./components/game/LeaderboardModal.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NeonButton: typeof import('./components/ui/NeonButton.vue')['default']
    NeonCard: typeof import('./components/ui/NeonCard.vue')['default']
    NeonCheckbox: typeof import('./components/ui/NeonCheckbox.vue')['default']
    NeonInput: typeof import('./components/ui/NeonInput.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    ProfileModal: typeof import('./components/game/ProfileModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnakeGame: typeof import('./components/game/SnakeGame.vue')['default']
    SpeedSelector: typeof import('./components/game/SpeedSelector.vue')['default']
  }
}
